#!/bin/bash

RUNS_NUMBER=10
EXECUTABLE_PATH=../build/nrp
SOLUTION_NUMBER=10
ROSTER_ITER_SECONDS=7
LIMIT=100
HCR=0
SPRINTS_FOLDER=../tests/sprints
OUTPUT_FOLDER=../tests/runs/$1
MODE='-t'


#python run.py -rn $RUNS_NUMBER -e $EXECUTABLE_PATH -n $SOLUTION_NUMBER -i $ROSTER_ITER_SECONDS -l $LIMIT -c $HCR -p "$SPRINTS_FOLDER/sprint_txt" -o "$OUTPUT_FOLDER/sprint" $MODE
#python run.py -rn $RUNS_NUMBER -e $EXECUTABLE_PATH -n $SOLUTION_NUMBER -i $ROSTER_ITER_SECONDS -l $LIMIT -c $HCR -p "$SPRINTS_FOLDER/sprint_hidden_txt" -o "$OUTPUT_FOLDER/sprint_hidden" $MODE
#python run.py -rn $RUNS_NUMBER -e $EXECUTABLE_PATH -n $SOLUTION_NUMBER -i $ROSTER_ITER_SECONDS -l $LIMIT -c $HCR -p "$SPRINTS_FOLDER/sprint_late_txt" -o "$OUTPUT_FOLDER/sprint_late" $MODE
python run.py -rn $RUNS_NUMBER -e $EXECUTABLE_PATH -n $SOLUTION_NUMBER -i $ROSTER_ITER_SECONDS -l $LIMIT -c $HCR -p "$SPRINTS_FOLDER/sprint_hint_txt" -o "$OUTPUT_FOLDER/sprint_hint" $MODE
